version: '3.7'

# For connection urls to the following instances, see
# https://github.com/prisma/prisma/blob/main/TESTING.md#environment-variables
services:
  mongodb_migrate:
    image: mongo:4
    restart: always
    ports:
      - '27017:27017'
  mongo:
    build: ./mongodb_replica
    environment:
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27018
    ports:
      - '27018:27018'
